sudo: false
dist: trusty

matrix:
  include:
  - language: php
    php: 7.2
  - language: php
    php: 7.1
  - language: php
    php: 7.0
  - language: php
    php: 5.6

cache:
  directories:
  - $HOME/.composer/cache

install:
- composer install --prefer-dist

script:
# broken due to namespaces
#- php vendor/bin/phpcs --standard=PSR2 shaarli2twitter tests
- php vendor/bin/phpunit --configuration ./phpunit.xml tests
